### ISSUE TITLE
No method found matching route super-resolution/ for http method POST.

### ISSUE THREAD

**Issue by SnakeO** [awslabs/aws-ai-solution-kit#152]
I've tried deploying this with and without authentication. I can get other endpoints to work (like pornography detection), however this endpoint (although it shows up in the "output" section) always returns this error:

```
{
    "message": "No method found matching route super-resolution/ for http method POST."
}
```

**Comment by yanbasic** [comment]
Hi, Please try to use ```super-resolution-ml/``` for calling this API.

Thanks,
Yi

**Comment by SnakeO** [comment]
Thank you so much Mr. Yi. 

The new endpoint works, and works well with very small images. Is there any way to increase the 30 second timeout limit for receiving the response upscaled image? I sometimes get this:

`{"message": "Endpoint request timed out"}`

**Comment by yanbasic** [comment]
Hi, It's a hard limit for the API Gateway [Integration timeout](https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html), so you cannot use it if the entire processing time exceeds 30 seconds, please try to invoke the SageMaker endpoint directly by Lambda or other services for the *asynchronous invocation*, more detail and sample code can be found [here](https://docs.aws.amazon.com/sagemaker/latest/dg/realtime-endpoints-test-endpoints.html).

Thanks,
Yi
