### ISSUE TITLE
go 1.x runtime is no longer supported

### ISSUE THREAD

**Issue by t089** [awslabs/aws-ai-solution-kit#155]
## Expected Behavior

Being able to deploy the template.

## Current Behavior

CloudFormation errors out because of deprecated go1.x runtime.

## Possible Solution

Move to `provided.al2` or `provided.al2023` runtimes.

Simply changing the value in the template does not seem to work though as the bootstrap handler is not found then.

```
Error: Couldn't find valid bootstrap(s): [/var/task/bootstrap /opt/bootstrap] Runtime.InvalidEntrypoint
```

## How to reproduce (for bugs)

**Comment by yike5460** [comment]
Thanks for reaching out, the issue has been resolved.
