### ISSUE TITLE
image super-resolution timeout / internal error

### ISSUE THREAD

**Issue by zxkane** [awslabs/aws-ai-solution-kit#2]
Use super-resolution with `inf1` instance, I tried `inf1.xlarge` and `inf1.6xlarge`.

When super-resolution a large pixel image(4000x3000), got below errors,

- internal error when using `inf1.xlarge` instance
- timeout when using `inf1.6xlarge` instance

If the resolution of image can not be supported, pls give the friendly error message, like http status `4xx` with proper information.

**Comment by yanbasic** [comment]
Hi @zxkane ,thanks for your report. This issue has been fix with the 1.2.0 release, if you are still using the Image Super Resolution feature, please deploy/upgrade the latest solution/project by this guide: https://awslabs.github.io/aws-ai-solution-kit/en/ . You could find more new features with the 1.2.0 release.
