### ISSUE TITLE
api returns status 200 even the internal error happens

### ISSUE THREAD

**Issue by zxkane** [awslabs/aws-ai-solution-kit#3]
it’s related to use case in #2 ,

When super-resolution an image with internal error, however the API still responses http status **200**. The error msg also expose the some internal information, such as account id.

**Comment by yanbasic** [comment]
Hi @zxkane ,thanks for your report. This issue has been fix with the 1.2.0 release, if you are still using the Image Super Resolution feature, please deploy/upgrade the latest solution/project by this guide: https://awslabs.github.io/aws-ai-solution-kit/en/ . You could find more new features with the 1.2.0 release.

Thanks for your interest.
