### ISSUE TITLE
Stack fails on PornographyDetection installation

### ISSUE THREAD

**Issue by gotters** [awslabs/aws-ai-solution-kit#95]
## Expected Behavior
Template should create stack

## Current Behavior
Template fails

## How to reproduce (for bugs)
Import template and create stack with PornographyDetection | yes-lambda enabled

Stack creation fails with the following error, no other info provided.
Embedded stack arn:aws:cloudformation:us-east-1:948320724766:stack/AIImageDetector-PornographyDetectionNestedStackPornographyDetectionNestedStackResource-36PDX2AQZ7GR/b095a010-8c33-11ed-8a72-1232682a975b was not successfully created: The following resource(s) failed to create: [pornographydetectionpornographydetectionAppDCBBB4C1].

**Comment by NingLu** [comment]
Hi @gotters 

I can't reproduce it in us-east-1, would you provide more details such as the CFN template url, the parameters you set?

and is there any more error messages? you will see the error by scrolling down in CloudFormation event tab

**Comment by NingLu** [comment]
<img width="1517" alt="Screen Shot 2023-01-05 at 09 17 34" src="https://user-images.githubusercontent.com/7640872/210680338-dab8f67c-110e-47e8-ac4c-afc0dc3aa68b.png">

**Comment by gotters** [comment]
I launched the template from your readme as per your launch link:
https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/create/template?stackName=AI-Solution-Kit&templateURL=https://aws-gcr-solutions.s3.amazonaws.com/Aws-gcr-ai-solution-kit/v1.3.0/AI-Solution-Kit.template

My parameters are the same as yours:
![image](https://user-images.githubusercontent.com/10713228/210716678-e3ffabf7-455f-487c-bb2e-3bd712a48f85.png)

Could it have something to do with this? Do I need some specific Role or IAM Resource setup first?
![image](https://user-images.githubusercontent.com/10713228/210716758-910c80af-f816-4d5f-ba14-081bb1781174.png)

There is no useful or helpful error info. It fails on this below...and then rolls back. No other errors. How can I find out more regarding what is failing?
![image](https://user-images.githubusercontent.com/10713228/210716978-f388aa03-8bbf-4a05-803b-3a44db144899.png)

Thanks for your help

**Comment by gotters** [comment]
I tried again without rollback and this time got more details in the error.

![image](https://user-images.githubusercontent.com/10713228/210721385-8054c7d5-1ec5-4b0b-89a0-9a185218821d.png)

How do I resolve this?
Thanks

**Comment by nowfox** [comment]
https://awslabs.github.io/aws-ai-solution-kit/en/faq/ ,Q3

**Comment by gotters** [comment]
Thanks for the reply

But my memory settings in AWS Lambda are set to 10,290 MB (as per
screenshot). I don't even have the ability to request more - i think that
is max.
[image: image.png]
How do I create a lamba function with a specific memory size? I can create
a 3.9 Python function but no option to specify memory?

Thanks

**Comment by yanbasic** [comment]
Hi @gotters, once the Lambda function has been created, the memory can be updated in the **General Configuration** tag, in the *Memory*, default is 128MB, the value can be set to 10240 MB for test.

Thanks,
<img width="930" alt="iShot_2023-01-06_09 04 13" src="https://user-images.githubusercontent.com/1256820/210908934-10d3fbb1-6230-4036-8e57-3f2dee65b875.png">

**Comment by gotters** [comment]
Thanks you're correct. I get the same error trying to set memory to 4096 MB.
But the resources show my max is 10240MB - do you know why it would be
doing this?

**Comment by yanbasic** [comment]
Hi @gotters, thanks for your confirmation, it seems you have to request to increase the memory limit in your account, if you just want to deploy the PornographyDetection feature, you can also reduce the memory to 3008 in the source code here: https://github.com/awslabs/aws-ai-solution-kit/blob/main/src/api-deployment/ai-solution-kit-stack.ts#L412 and deploy the feature by CDK deploy, it might be a bit slowly than the default memory size.

**Comment by gotters** [comment]
Ok thank you. For some reason I don't have the ability to request a quota
increase. I dont know why.
In the end I deployed it to sageMaker - is there a significant difference?

Unfortunately after some testing I dont think its going to help me. I have
a difficult use case scenario where I need images of screenshots that have
been blurred to be analyzed. I think given that its a screenshot - which
can contain multiple parts and not just one image - and the fact that it is
slightly blurred - is making the detection algorithm ineffective.

Can you confirm?
Thanks
Moshe

**Comment by yanbasic** [comment]
Hi @gotters, the Lambda and SageMaker models are the same result, the SageMaker based feature will create a SageMaker instance, you can undeploy the feature after you test it to avoid additional cost in your account. The model for pornography detection is trained by common sample dataset, I'm afraid it cannot detect the 'blurred' images, did you try to detect only one image to see the result is correct?

**Comment by gotters** [comment]
Thanks for the info.

I thought i would try the enhance image resolution feature, followed by the
pornography detection - do you think that would help?
I deleted my previous stack which had the porn detector in sage maker and
tried creating a new one with both in sage maker but now its failing
completely with the errors below. But I cant see those resources?

 Resource handler returned message: "Resource of type
'AWS::ECR::Repository' with identifier
'ai-solution-kit-super-resolution-sagemaker' already exists."
(RequestToken: 6268e451-0e98-58b6-9211-a17131e59435, HandlerErrorCode:
AlreadyExists)

Resource handler returned message: "Resource of type 'AWS::ECR::Repository'
with identifier 'ai-solution-kit-pornography-detection-sagemaker' already
exists." (RequestToken: 8b01d46d-7787-466c-f042-77438c6a03af,
HandlerErrorCode: AlreadyExists)

**Comment by yanbasic** [comment]
I'm afraid the Super Resolution might not help for your case, for the above error you can open AWS ECR web console and delete the related repositories before deploy the new CloudFormation stack. What's the detection result for the Pornography Detection API?
